# app EC2 instance (set in docs/aws-ec2-setup.md)
# Jenkins will pass SSH private key to Ansible via:
#   ansible-playbook ... --private-key "$SSH_KEY"

[sewdl_app]
app ansible_host=13.201.44.89 ansible_user=ubuntu

[sewdl_app:vars]
ansible_python_interpreter=/usr/bin/python3
